spring.datasource.url=jdbc:h2:mem:librarytestdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=VGhpc0lzQVRlc3RTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkw
jwt.expiration=86400000
jwt.refresh-expiration=604800000