spring.datasource.url=jdbc:h2:mem:librarytestdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=NDgyZmY4YjQzMjQ4YTFjZTA5MTUyNzYzNDgxYzVjZTQ4MjNlYjc1ZTQ0OTYwMzQ0OTk0MzE0YzM4YTY0MjM4YQ==
jwt.expiration=86400000